version: 2

jobs:
  docker:
    image: circleci/docker@1.0.1
  deploy:
    steps:
      - checkout
      - run:
          name: deploy to heroku
          command: |
            docker login --username=$HEROKU_USERNAME --password=$HEROKU_PASSWORD $REGISTRY_DOMAIN
            docker tag londes/docker-hy:latest $REGISTRY_DOMAIN/$TARGET_REPOSITORY
            docker push $REGISTRY_DOMAIN/$TARGET_REPOSITORY

workflows:
  deploy_to_heroku:
    jobs:
      - deploy
