name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: heroku push
        run: |
          docker login --username=${{secrets.HEROKU_EMAIL}} --password=${{secrets.HEROKU_API_KEY}}
          docker tag londes/docker-hy:latest registry.heroku.com/frozen-chamber-94298/web
          docker push registry.heroku.com/frozen-chamber-94298/web
