name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  push:
    runs-on: ubuntu-latest
    steps:
      - name: heroku push
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}} 
        run: |
          heroku container:login
          heroku container:push -a ${{secrets.HEROKU_APP_NAME}} web
          heroku container:release -a ${{secrets.HEROKU_APP_NAME}} web
