name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: heroku login
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}} 
        run: heroku container:login
      - name: heroku push
        run: heroku container:push -a ${{secrets.HEROKU_APP_NAME}} web
      - name: heroku release
        run: heroku container:release -a ${{secrets.HEROKU_APP_NAME}} web
