name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  push:
    runs-on: ubuntu-latest
    steps:
      - name: heroku push
        run: |
          echo ${{secrets.HEROKU_API_KEY}} | docker login --username=${{secrets.HEROKU_EMAIL}} --password-stdin registry.heroku.com
          docker tag londes/docker-hy:latest registry.heroku.com/${{secrets.HEROKU_APP_NAME}}/web
          docker push registry.heroku.com/${{secrets.HEROKU_APP_NAME}}/web
